name: app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.3.8
  get_storage: 2.0.3
  easy_mask: 1.1.5
  flutter_svg: 0.22.0
  sliding_up_panel: 2.0.0+1
  loading_overlay: 0.3.0
  page_indicator: 0.4.1
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lang/
    - assets/images/
